openapi: 3.0.3
info:
  title: API de Metas Gamificadas
  description: Microserviço para criação e acompanhamento de metas de saúde com gamificação.
  version: 1.0.0

servers:
  - url: https://api.seuapp.com/v1

paths:
  /metas:
    post:
      summary: Criar uma nova meta
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MetaRequest'
      responses:
        '201':
          description: Meta criada com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MetaResponse'
    get:
      summary: Listar todas as metas
      responses:
        '200':
          description: Lista de metas
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MetaResponse'

  /metas/{meta_id}:
    get:
      summary: Obter detalhes de uma meta
      parameters:
        - name: meta_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Detalhes da meta
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MetaResponse'
        '404':
          description: Meta não encontrada

    put:
      summary: Atualizar uma meta existente
      parameters:
        - name: meta_id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MetaRequest'
      responses:
        '200':
          description: Meta atualizada com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MetaResponse'
        '404':
          description: Meta não encontrada

    delete:
      summary: Excluir uma meta
      parameters:
        - name: meta_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Meta excluída com sucesso
        '404':
          description: Meta não encontrada

  /metas/{meta_id}/progresso:
    patch:
      summary: Atualizar progresso de uma meta
      description: Registra conquistas parciais e atualiza recompensas.
      parameters:
        - name: meta_id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProgressoRequest'
      responses:
        '200':
          description: Progresso atualizado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MetaResponse'
        '404':
          description: Meta não encontrada

components:
  schemas:
    MetaRequest:
      type: object
      required:
        - usuario_id
        - titulo
        - categoria
        - tipo
        - data_inicio
      properties:
        usuario_id:
          type: string
          example: "12345"
        titulo:
          type: string
          example: "Caminhar 30 minutos por dia"
        descricao:
          type: string
          example: "Meta para aumentar atividade física diária"
        categoria:
          type: string
          enum: [saúde_física, saúde_mental, nutrição]
        tipo:
          type: string
          enum: [diária, semanal, mensal, pontual]
        data_inicio:
          type: string
          format: date
          example: "2026-02-08"
        data_fim:
          type: string
          format: date
          example: "2026-03-08"
        frequencia:
          type: object
          properties:
            periodicidade:
              type: string
              example: "diária"
            vezes_por_periodo:
              type: integer
              example: 1
        dificuldade:
          type: string
          enum: [fácil, média, difícil]
        recompensa:
          type: object
          properties:
            pontos:
              type: integer
              example: 50
            badge:
              type: string
              example: "walker"
        status:
          type: string
          enum: [ativa, concluída, arquivada]
        notificacoes:
          type: boolean
          example: true

    MetaResponse:
      type: object
      properties:
        meta_id:
          type: string
          example: "98765"
        usuario_id:
          type: string
          example: "12345"
        titulo:
          type: string
          example: "Caminhar 30 minutos por dia"
        status:
          type: string
          example: "ativa"
        data_criacao:
          type: string
          format: date-time
          example: "2026-02-08T12:22:00Z"
        progresso:
          type: object
          properties:
            concluido:
              type: integer
              example: 5
            total:
              type: integer
              example: 30
            unidade:
              type: string
              example: "dias"
        gamificacao:
          type: object
          properties:
            pontos_atribuidos:
              type: integer
              example: 100
            badge:
              type: string
              example: "walker"
            nivel_usuario:
              type: integer
              example: 4
        mensagem:
          type: string
          example: "Progresso atualizado! Você completou 5 de 30 dias e ganhou 50 pontos."

    ProgressoRequest:
      type: object
      required:
        - incremento
      properties:
        incremento:
          type: integer
          example: 1
        unidade:
          type: string
          example: "dias"
